apiVersion: v1
kind: Service
metadata:
  name: master-api-service
  namespace: development
  labels:
    app: master-api
spec:
  selector:
    app: master-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer