apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-api
  namespace: development
  labels:
    app: master-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-api
  template:
    metadata:
      name: master-api
      labels:
        app: master-api
    spec:
      containers:
      - name: master-api
        image: master-api:2
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
