apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: development
  labels:
    app: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      name: rest-api
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: rest:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
